[package]
name = "rustorrent"
version = "0.1.0"
authors = ["Sebastien Chapuis <sebastien@chapu.is>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_bencode = "^0.2.0"
serde = { version = "1.0", features = ["derive"] }
serde_derive = "^1.0.0"

async-std = "1"
surf = "1.0.3"
